micronaut:
  application:
    name: blockingdemoclient
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: 7999
    netty:
      worker:
        threads: 10000
      parent:
        threads: 10000
  http:
    services:
      server:
        url: http://localhost:8080/
        path: "/blockingdemo/"
        read-timeout: 10s
        num-of-threads: 10000
      mdc:
        url: http://localhost:8001/
        path: "/api/v1/logging-context"
        read-timeout: 10s
        num-of-threads: 10000
netty:
  default:
    allocator:
      max-order: 3
