micronaut:
  application:
    name: blockingdemoclient
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: 8001
  http:
    services:
      server:
        url: http://localhost:8080/
        path: "/blockingdemo/"
        read-timeout: 10s
        num-of-threads: 10000
netty:
  default:
    allocator:
      max-order: 3
