micronaut:
  application:
    name: blockingdemo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    netty:
      worker:
        threads: 10000
      parent:
        threads: 10000
netty:
  default:
    allocator:
      max-order: 3
